name: ubuntu_ci-16.04

on: 
  push:
    paths:
      - 'rt_smart/**'
      - '.github/workflows/rt_smart.yml'
  pull_request:
    paths:
      - 'rt_smart/**'
      - '.github/workflows/rt_smart.yml'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 中国镜像版本
      - name: build china
        uses: docker/build-push-action@v3
        if: github.ref_name != 'master'
        with:
          context: rt_smart/china
          file: ./rt_smart/china/Dockerfile
          tags: csplink/rt_smart:china

      - name: build and push china
        uses: docker/build-push-action@v3
        if: github.ref_name == 'master'
        with:
          push: true
          context: rt_smart/china
          file: ./rt_smart/china/Dockerfile
          tags: csplink/rt_smart:china

      # 美国镜像版本
      - name: build us
        uses: docker/build-push-action@v3
        if: github.ref_name != 'master'
        with:
          context: rt_smart/us
          file: ./rt_smart/us/Dockerfile
          tags: csplink/rt_smart:us

      - name: build and push us
        uses: docker/build-push-action@v3
        if: github.ref_name == 'master'
        with:
          push: true
          context: rt_smart/us
          file: ./rt_smart/us/Dockerfile
          tags: csplink/rt_smart:us
