name: ubuntu_ci-18.04

on: 
  push:
    paths:
      - 'ubuntu_ci/18.04/**'
      - '.github/workflows/ubuntu_ci-18.04.yml'
  pull_request:
    paths:
      - 'ubuntu_ci/18.04/**'
      - '.github/workflows/ubuntu_ci-18.04.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build 
        uses: docker/build-push-action@v3
        if: github.ref_name != 'master'
        with:
          context: ubuntu_ci/18.04
          file: ./ubuntu_ci/18.04/Dockerfile
          tags: csplink/ubuntu_ci:18.04

      - name: build and push
        uses: docker/build-push-action@v3
        if: github.ref_name == 'master'
        with:
          push: true
          context: ubuntu_ci/18.04
          file: ./ubuntu_ci/18.04/Dockerfile
          tags: csplink/ubuntu_ci:18.04