name: ci

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: echo
        run: 
          echo ${{ github.path }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: user/app:latest